# Análise: Dados do Campeonato Brasileiro de Futebol (2003 até 2022)

## Importação de Pacotes

In [1]:
# Imports
import pandas as pd

## Carga dos Dados

In [2]:
df_partidas = pd.read_csv('dados/campeonato-brasileiro-full.csv')
df_estatisticas = pd.read_csv('dados/campeonato-brasileiro-estatisticas-full.csv')
df_gols = pd.read_csv('dados/campeonato-brasileiro-gols.csv')
df_cartoes = pd.read_csv('dados/campeonato-brasileiro-cartoes.csv')

## Análise exploratória

In [3]:
df_partidas

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
0,1,1,29/3/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ
1,2,1,29/3/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS
2,3,1,30/3/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR
3,4,1,30/3/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA
4,5,1,30/3/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8020,8021,38,13/11/2022,16:03,Cuiaba,Coritiba,4-1-4-1,4-1-4-1,A. Cardoso de Oliveira,A. Ferreira,Cuiaba,Arena Pantanal,2,1,MT,PR
8021,8022,38,13/11/2022,16:03,Bragantino,Fluminense,4-2-3-1,4-2-3-1,M. Nogueira Barbieri,F. Diniz Silva,Fluminense,Nabizão,0,1,SP,RJ
8022,8023,38,13/11/2022,16:03,Corinthians,Atletico-MG,4-1-4-1,4-2-3-1,F. J. Monteiro Almeida,A. Stival,Atletico-MG,Neo Química Arena,0,1,SP,MG
8023,8024,38,13/11/2022,16:03,Internacional,Palmeiras,4-2-3-1,4-2-3-1,L. Venker de Menezes,A. Moreira Ferreira,Internacional,Estádio José Pinheiro Borda,3,0,RS,SP
8024,8025,38,13/11/2022,16:03,Goias,Sao Paulo,4-2-3-1,4-1-2-1-2,J. Ribeiro Ventura,R. Ceni,Sao Paulo,Estádio da Serrinha,0,4,GO,SP

In [4]:
df_estatisticas

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Flamengo,0,0,NaN,0,NaN,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16045,8023,38,Atletico-MG,17,7,41%,351,82%,19,6,0,0,4
16046,8024,38,Internacional,15,8,48%,287,77%,13,2,0,1,6
16047,8024,38,Palmeiras,11,2,52%,306,82%,17,3,0,2,5
16048,8025,38,Goias,6,2,35%,330,80%,12,2,0,1,3
16049,8025,38,Sao Paulo,13,7,65%,591,90%,14,1,0,0,4

In [5]:
df_cartoes

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
1,4608,1,Internacional,Amarelo,Andrés D'Alessandro,10.0,Meio-campo,72
2,4608,1,Vitoria,Amarelo,Marcelo Machado dos Santos,29.0,NaN,86
3,4608,1,Vitoria,Amarelo,Mansur,NaN,Zagueiro,10
4,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44
...,...,...,...,...,...,...,...,...
16734,8023,38,Atletico-MG,Amarelo,Jemerson de Jesus Nascimento,34.0,Zagueiro,45+2
16735,8024,38,Internacional,Amarelo,Lucas Ramos,37.0,Meio-campo,80
16736,8024,38,Palmeiras,Amarelo,José Manuel Alberto López,18.0,Meio-campo,88
16737,8024,38,Palmeiras,Amarelo,Eduard Atuesta,20.0,Meio-campo,23
16738,8025,38,Goias,Amarelo,Magno Jose da Silva,2.0,Zagueiro,40

In [6]:
df_gols

,partida_id,rodata,clube,atleta,minuto,tipo_de_gol
0,4607,1,Fluminense,Fred,45,Penalty
1,4607,1,Fluminense,Nirley da Silva Fonseca,59,Gol Contra
2,4607,1,Fluminense,Rafael Sóbis,31,NaN
3,4608,1,Internacional,Charles Aránguiz,6,NaN
4,4611,1,Sao Paulo,Antônio Carlos dos Santos Aguiar,13,NaN
...,...,...,...,...,...,...
7981,8019,38,Atletico-GO,Dudu,17,NaN
7982,8021,38,Cuiaba,Jonathan Cafú,44,NaN
7983,8024,38,Internacional,Alexandre Alemão,39,NaN
7984,8025,38,Sao Paulo,Marcos Guilherme,77,NaN
7985,8018,38,Ceara,Erick,89,Penalty

## Tratamento de Valores Ausentes

In [7]:
# Função: Percentual Valores Ausentes por Variável
def func_percent_values_missing_column(df):
  missingCount = df.isnull().sum()
  missingPercent = 100 * missingCount / len(df)
  missingType = df.dtypes
  missingTable = pd.concat([missingCount, missingPercent, missingType], axis = 1)
  mis_table_ren_columns = missingTable.rename(columns = {0: 'Valores Ausentes', 1: '% de Valores Ausentes', 2: 'Dtype'})
  mis_table_ren_columns = mis_table_ren_columns[mis_table_ren_columns.iloc[:,0] != 0].sort_values('% de Valores Ausentes', ascending = False).round(2)
  print("O dataset tem " + str(df.shape[1]) + " colunas. \nEncontrando: " + str(mis_table_ren_columns.shape[0]) + " colunas que têm valores ausentes.")
  if mis_table_ren_columns.shape[0] == 0:
    return
  return mis_table_ren_columns

In [8]:
# Percentual de Valores Ausentes: df_partidas
df_partidas_ausentes = func_percent_values_missing_column(df_partidas)
df_partidas_ausentes

O dataset tem 16 colunas.
Encontrando: 4 colunas que têm valores ausentes.

                    Valores Ausentes  % de Valores Ausentes   Dtype
formacao_mandante               4974                  61.98  object
formacao_visitante              4974                  61.98  object
tecnico_mandante                4610                  57.45  object
tecnico_visitante               4610                  57.45  object

### Merge dos DataFrames df_

In [9]:
df_partidas = df_partidas.rename(columns = {'ID': 'partida_id'})

In [10]:
df = pd.merge(df_partidas, df_estatisticas, on=['partida_id', 'rodata'], how='inner')
df

,partida_id,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,...,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,29/3/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,...,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,29/3/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,...,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,29/3/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,...,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,29/3/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,...,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,30/3/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,...,0,0,NaN,0,NaN,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16045,8023,38,13/11/2022,16:03,Corinthians,Atletico-MG,4-1-4-1,4-2-3-1,F. J. Monteiro Almeida,A. Stival,...,17,7,41%,351,82%,19,6,0,0,4
16046,8024,38,13/11/2022,16:03,Internacional,Palmeiras,4-2-3-1,4-2-3-1,L. Venker de Menezes,A. Moreira Ferreira,...,15,8,48%,287,77%,13,2,0,1,6
16047,8024,38,13/11/2022,16:03,Internacional,Palmeiras,4-2-3-1,4-2-3-1,L. Venker de Menezes,A. Moreira Ferreira,...,11,2,52%,306,82%,17,3,0,2,5
16048,8025,38,13/11/2022,16:03,Goias,Sao Paulo,4-2-3-1,4-1-2-1-2,J. Ribeiro Ventura,R. Ceni,...,6,2,35%,330,80%,12,2,0,1,3
16049,8025,38,13/11/2022,16:03,Goias,Sao Paulo,4-2-3-1,4-1-2-1-2,J. Ribeiro Ventura,R. Ceni,...,13,7,65%,591,90%,14,1,0,0,4

Por decisão de negócio, irei excluir as colunas tecnico_mandante e tecnico_visitante pelo percentual de valores ausentes e por representar informações que não irão ser usadas na análise

In [12]:
df_partidas.drop(columns=["tecnico_mandante", "tecnico_visitante", "formacao_mandante", "formacao_visitante"])

,partida_id,rodata,data,hora,mandante,visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
0,1,1,29/3/2003,16:00,Guarani,Vasco,Guarani,Brinco de Ouro,4,2,SP,RJ
1,2,1,29/3/2003,16:00,Athletico-PR,Gremio,Athletico-PR,Arena da Baixada,2,0,PR,RS
2,3,1,30/3/2003,16:00,Flamengo,Coritiba,-,Maracanã,1,1,RJ,PR
3,4,1,30/3/2003,16:00,Goias,Paysandu,-,Serra Dourada,2,2,GO,PA
4,5,1,30/3/2003,16:00,Internacional,Ponte Preta,-,Beira Rio,1,1,RS,SP
...,...,...,...,...,...,...,...,...,...,...,...,...
8020,8021,38,13/11/2022,16:03,Cuiaba,Coritiba,Cuiaba,Arena Pantanal,2,1,MT,PR
8021,8022,38,13/11/2022,16:03,Bragantino,Fluminense,Fluminense,Nabizão,0,1,SP,RJ
8022,8023,38,13/11/2022,16:03,Corinthians,Atletico-MG,Atletico-MG,Neo Química Arena,0,1,SP,MG
8023,8024,38,13/11/2022,16:03,Internacional,Palmeiras,Internacional,Estádio José Pinheiro Borda,3,0,RS,SP
8024,8025,38,13/11/2022,16:03,Goias,Sao Paulo,Sao Paulo,Estádio da Serrinha,0,4,GO,SP